config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  get 'categories/update'
  get 'categories/destroy'
  get 'categories/new'
  get 'categories/edit'
 #Route racine ou nous allons lui dire ce qu'elle doit faire quand elle est à la racine.
  root to: 'pages#home'

# (/:name) = paramètre optionnelle 
  get '/welcome(/:name)', to: 'pages#salut', as: 'salut' 
# as: 'salut' = cette route là je vais l'appeler salut grâce _path (regade dans application.html.erb)
#En gros lorsque j'appelle l'url get '/welcome(/:name)' j'aurrai cette action to: 'pages#salut' et nous donnons un nom aux routes as: 'salut'. Les routes pointes vers les action dans le fichier controller

  resources :posts
  
  resources :categories
  
end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
#1) Est lié au Controller, CRUD
#2) ESt lié au Controller, filres
#3) Est lié au Controller, Sessions/cookies
#4) Est lié au Controller, différents formats
#5) Est lié au Models, Validation des données
#6) Est lié au Models, les callbacks

  
  
  
#2)Ce code sera efectué avant les méthodes index, show, ... grâce au filtre (il y en a différentes sortes) before_action (on peut vérifier dans le terminal)
  before_action do |controller|
    puts "$" * 60
    puts "Je suis avant l'action"
    puts "$" * 60
  end
  
  after_action do |controller|
    puts "$" * 60
    puts "Je suis après l'action"
    puts "$" * 60
  end
  
  def index
#3)Nous pouvons l'afficher dans la catégorie de la vue index.
    @session = session[:user_id]
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(the_method_category_params)
    redirect_to category_path(@category.id)
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(the_method_category_params)
    redirect_to category_path(@category.id)
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  private
  
  def the_method_category_params
    params.require(:category).permit(:name, :slug)
  end
  
#2)Permet d'entourer une action (yield)et prend le nom d'une méthode (sous forme d'atome). Mais il est rare d'utilisation
  around_action :around

  def around
    puts "€" * 60
    yield
    puts "€" * 60
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
 
<br>

<h1>Editer catégorie</h1>

<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.text_field :name, placeholder: 'Nom', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.text_field :slug, placeholder: 'URL', class: 'form-control' %>
  </div>

  <div class="form-group">
    <button class="btn btn-primary" type="submit">Modifier la catégorie</button>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1>Categories#index</h1>

<br><br><br><br>

<h1>Les catégories</h1>
<br>

<p>
  Session : <%= @session.inspect %>
</p>

<br>

<!-- 1)Affichage de toutes les catégories + bouton "editer" -->
<table class="table">
  <thead>
    <td>ID </td>
    <td>Nom </td>
    <td>Actions </td>
  </thead>
  <tbody>
    <tr>
      <% @categories.each do |category| %>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td>
          <a href="<%= edit_category_path(category.id) %>" class="btn btn-primary">Editer</a>
          <a href="<%= category_path(category.id) %>" class="btn btn-danger" data-confirm="Etes vous sûr ?" data-method="delete">Supprimer</a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- 1)Création du bouton "créer nouvelle catégorie" -->
<p>
  <a href="<%= new_category_path %>" class="btn btn-success">Créer une nouvelle catégorie</a>
</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>

<br>

<h1>Nouvelle catégorie</h1>

<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.text_field :name, placeholder: 'Nom', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.text_field :slug, placeholder: 'URL', class: 'form-control' %>
  </div>

  <div class="form-group">
    <button class="btn btn-primary" type="submit">Créer la catégorie</button>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>