config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  get 'categories/update'
  get 'categories/destroy'
  get 'categories/new'
  get 'categories/edit'
 #Route racine ou nous allons lui dire ce qu'elle doit faire quand elle est à la racine.
  root to: 'pages#home'

# (/:name) = paramètre optionnelle 
  get '/welcome(/:name)', to: 'pages#salut', as: 'salut' 
# as: 'salut' = cette route là je vais l'appeler salut grâce _path (regade dans application.html.erb)
#En gros lorsque j'appelle l'url get '/welcome(/:name)' j'aurrai cette action to: 'pages#salut' et nous donnons un nom aux routes as: 'salut'. Les routes pointes vers les action dans le fichier controller

  resources :posts
  
  resources :categories
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetGrafikart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
  </head>

  <body>
    <div class="navbar navbar-dark bg-dark shadow-sm">
      <div class="container">
        <a href="<%= root_path %>" class="navbar-brand d-flex align-items-center">
          <strong>Projet Grafikart</strong>
        </a>
        <li class="nav-item">
          <a class="nav-link" href="<%= salut_path(name: 'Ben') %>">Salut</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= posts_path %>">Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= categories_path %>">Catégories</a>
        </li>
      </div>
    </div>
    
    
    
<!-- 3) Permet de créer une alert success puis de le supprimer -->
    <div class="container" style="paddin-top: 5rem;">
      <!--
      <#% if session[:success] %>
        <div class="alert alert-success"><#%= session[:success] %></div>
        <#% session.delete(:success) %> 
      <#% end %>
-->
      
<!-- 3) Le flash permet de sauver quelque chose session et est supprimé à la prochaine requet (donc bcp plus pratique que la méthode ci-dessus!) -->
      <% if flash[:success] %>
        <div class="alert alert-success"><%= flash[:success] %></div>
      <% end %>
<!-- 3) Possibilité de boucler -->
      
      
      <%= yield %>
    </div> 
  
  
  
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>